### PR TITLE
Add support for non-default VPCs

### LINKED ISSUE #85: Destroy cluster "You may only modify the groupSet attribute for VPC instances"
When I run `flintrock destroy <cluster>` at a cluster outside of the VPC in AWS I get the message "You may only modify the groupSet attribute for VPC instances". I have noticed this is an issue for flintrock versions 0.2.0 and 0.3.0, but not for 0.1.0.

This is what I have for my config
```yaml
    # vpc-id: <id>
    # subnet-id: <id>
```

Here is the full output
```bash
flintrock destroy dale-lsh
dale-lsh:
  state: running
  node-count: 201
  master: ec2-50-19-147-60.compute-1.amazonaws.com
  slaves:
    - ec2-23-22-140-251.compute-1.amazonaws.com
    - ec2-50-17-126-74.compute-1.amazonaws.com
    - ec2-107-21-137-51.compute-1.amazonaws.com
    - ec2-54-91-95-67.compute-1.amazonaws.com
    - ec2-54-91-153-113.compute-1.amazonaws.com
    - ec2-54-227-87-108.compute-1.amazonaws.com
    - ec2-54-82-66-138.compute-1.amazonaws.com
    - ec2-54-221-0-134.compute-1.amazonaws.com
    - ec2-50-17-83-252.compute-1.amazonaws.com
    - ec2-54-167-26-223.compute-1.amazonaws.com
    - ec2-54-92-192-178.compute-1.amazonaws.com
    - ec2-54-90-150-249.compute-1.amazonaws.com
    - ec2-54-242-129-235.compute-1.amazonaws.com
    - ec2-54-87-28-208.compute-1.amazonaws.com
    - ec2-54-159-39-90.compute-1.amazonaws.com
    - ec2-54-242-160-161.compute-1.amazonaws.com
    - ec2-54-196-177-62.compute-1.amazonaws.com
    - ec2-54-144-65-225.compute-1.amazonaws.com
    - ec2-54-82-84-171.compute-1.amazonaws.com
    - ec2-54-227-60-71.compute-1.amazonaws.com
    - ec2-54-82-7-228.compute-1.amazonaws.com
    - ec2-54-221-111-109.compute-1.amazonaws.com
    - ec2-54-196-217-0.compute-1.amazonaws.com
    - ec2-54-226-248-200.compute-1.amazonaws.com
    - ec2-50-17-122-243.compute-1.amazonaws.com
    - ec2-54-160-203-126.compute-1.amazonaws.com
    - ec2-54-227-9-58.compute-1.amazonaws.com
    - ec2-54-145-62-121.compute-1.amazonaws.com
    - ec2-107-21-140-165.compute-1.amazonaws.com
    - ec2-54-147-131-121.compute-1.amazonaws.com
    - ec2-54-163-39-161.compute-1.amazonaws.com
    - ec2-54-147-168-163.compute-1.amazonaws.com
    - ec2-23-22-176-58.compute-1.amazonaws.com
    - ec2-54-147-182-91.compute-1.amazonaws.com
    - ec2-107-21-182-183.compute-1.amazonaws.com
    - ec2-54-147-11-170.compute-1.amazonaws.com
    - ec2-54-196-252-58.compute-1.amazonaws.com
    - ec2-54-90-180-190.compute-1.amazonaws.com
    - ec2-54-226-53-187.compute-1.amazonaws.com
    - ec2-54-167-98-196.compute-1.amazonaws.com
    - ec2-54-242-101-14.compute-1.amazonaws.com
    - ec2-54-90-163-36.compute-1.amazonaws.com
    - ec2-54-144-87-126.compute-1.amazonaws.com
    - ec2-54-82-81-212.compute-1.amazonaws.com
    - ec2-54-83-77-11.compute-1.amazonaws.com
    - ec2-54-221-98-203.compute-1.amazonaws.com
    - ec2-54-242-125-165.compute-1.amazonaws.com
    - ec2-54-221-150-81.compute-1.amazonaws.com
    - ec2-54-83-91-99.compute-1.amazonaws.com
    - ec2-54-160-134-176.compute-1.amazonaws.com
    - ec2-54-83-111-115.compute-1.amazonaws.com
    - ec2-54-92-217-202.compute-1.amazonaws.com
    - ec2-54-146-201-97.compute-1.amazonaws.com
    - ec2-23-22-170-108.compute-1.amazonaws.com
    - ec2-54-196-164-225.compute-1.amazonaws.com
    - ec2-54-221-12-243.compute-1.amazonaws.com
    - ec2-54-145-30-139.compute-1.amazonaws.com
    - ec2-54-234-31-227.compute-1.amazonaws.com
    - ec2-54-242-3-71.compute-1.amazonaws.com
    - ec2-54-167-33-215.compute-1.amazonaws.com
    - ec2-54-221-130-212.compute-1.amazonaws.com
    - ec2-54-160-193-240.compute-1.amazonaws.com
    - ec2-54-242-85-70.compute-1.amazonaws.com
    - ec2-54-196-252-93.compute-1.amazonaws.com
    - ec2-54-82-16-116.compute-1.amazonaws.com
    - ec2-54-226-5-51.compute-1.amazonaws.com
    - ec2-54-82-93-114.compute-1.amazonaws.com
    - ec2-54-196-217-119.compute-1.amazonaws.com
    - ec2-54-146-253-138.compute-1.amazonaws.com
    - ec2-54-234-169-195.compute-1.amazonaws.com
    - ec2-54-147-4-167.compute-1.amazonaws.com
    - ec2-54-163-20-244.compute-1.amazonaws.com
    - ec2-54-91-151-170.compute-1.amazonaws.com
    - ec2-54-160-170-38.compute-1.amazonaws.com
    - ec2-50-19-24-139.compute-1.amazonaws.com
    - ec2-54-242-39-79.compute-1.amazonaws.com
    - ec2-54-196-252-148.compute-1.amazonaws.com
    - ec2-54-90-131-236.compute-1.amazonaws.com
    - ec2-54-145-23-5.compute-1.amazonaws.com
    - ec2-54-90-141-112.compute-1.amazonaws.com
    - ec2-54-91-161-130.compute-1.amazonaws.com
    - ec2-54-234-205-204.compute-1.amazonaws.com
    - ec2-54-234-174-232.compute-1.amazonaws.com
    - ec2-54-221-52-6.compute-1.amazonaws.com
    - ec2-54-90-222-69.compute-1.amazonaws.com
    - ec2-50-17-96-127.compute-1.amazonaws.com
    - ec2-54-234-74-87.compute-1.amazonaws.com
    - ec2-54-145-48-130.compute-1.amazonaws.com
    - ec2-54-87-19-80.compute-1.amazonaws.com
    - ec2-54-145-29-229.compute-1.amazonaws.com
    - ec2-54-167-81-203.compute-1.amazonaws.com
    - ec2-54-163-201-254.compute-1.amazonaws.com
    - ec2-54-234-39-250.compute-1.amazonaws.com
    - ec2-54-227-43-155.compute-1.amazonaws.com
    - ec2-54-234-153-24.compute-1.amazonaws.com
    - ec2-107-20-99-232.compute-1.amazonaws.com
    - ec2-54-226-248-225.compute-1.amazonaws.com
    - ec2-54-242-164-178.compute-1.amazonaws.com
    - ec2-50-19-55-113.compute-1.amazonaws.com
    - ec2-54-145-49-16.compute-1.amazonaws.com
    - ec2-54-90-164-138.compute-1.amazonaws.com
    - ec2-54-242-113-241.compute-1.amazonaws.com
    - ec2-54-234-242-55.compute-1.amazonaws.com
    - ec2-54-196-219-173.compute-1.amazonaws.com
    - ec2-54-146-225-132.compute-1.amazonaws.com
    - ec2-54-167-98-222.compute-1.amazonaws.com
    - ec2-23-22-235-210.compute-1.amazonaws.com
    - ec2-54-196-155-223.compute-1.amazonaws.com
    - ec2-54-227-63-240.compute-1.amazonaws.com
    - ec2-54-163-221-149.compute-1.amazonaws.com
    - ec2-23-22-128-131.compute-1.amazonaws.com
    - ec2-54-90-140-98.compute-1.amazonaws.com
    - ec2-54-146-225-214.compute-1.amazonaws.com
    - ec2-54-227-99-115.compute-1.amazonaws.com
    - ec2-54-226-72-96.compute-1.amazonaws.com
    - ec2-107-21-179-244.compute-1.amazonaws.com
    - ec2-54-196-154-183.compute-1.amazonaws.com
    - ec2-54-242-150-234.compute-1.amazonaws.com
    - ec2-54-234-82-196.compute-1.amazonaws.com
    - ec2-107-21-149-201.compute-1.amazonaws.com
    - ec2-54-242-137-4.compute-1.amazonaws.com
    - ec2-54-221-3-134.compute-1.amazonaws.com
    - ec2-54-87-50-255.compute-1.amazonaws.com
    - ec2-54-83-97-25.compute-1.amazonaws.com
    - ec2-54-82-41-132.compute-1.amazonaws.com
    - ec2-54-242-144-253.compute-1.amazonaws.com
    - ec2-107-20-75-192.compute-1.amazonaws.com
    - ec2-54-90-64-117.compute-1.amazonaws.com
    - ec2-54-227-74-149.compute-1.amazonaws.com
    - ec2-54-221-106-93.compute-1.amazonaws.com
    - ec2-54-242-155-101.compute-1.amazonaws.com
    - ec2-107-20-56-139.compute-1.amazonaws.com
    - ec2-54-159-21-137.compute-1.amazonaws.com
    - ec2-54-226-98-59.compute-1.amazonaws.com
    - ec2-54-167-72-19.compute-1.amazonaws.com
    - ec2-54-91-133-83.compute-1.amazonaws.com
    - ec2-54-87-27-214.compute-1.amazonaws.com
    - ec2-23-22-155-98.compute-1.amazonaws.com
    - ec2-54-83-126-252.compute-1.amazonaws.com
    - ec2-54-234-193-71.compute-1.amazonaws.com
    - ec2-54-226-237-110.compute-1.amazonaws.com
    - ec2-54-144-98-168.compute-1.amazonaws.com
    - ec2-50-17-102-207.compute-1.amazonaws.com
    - ec2-54-196-251-245.compute-1.amazonaws.com
    - ec2-54-160-253-189.compute-1.amazonaws.com
    - ec2-50-17-107-48.compute-1.amazonaws.com
    - ec2-54-144-82-7.compute-1.amazonaws.com
    - ec2-54-196-220-111.compute-1.amazonaws.com
    - ec2-54-167-55-184.compute-1.amazonaws.com
    - ec2-54-160-163-166.compute-1.amazonaws.com
    - ec2-23-22-178-67.compute-1.amazonaws.com
    - ec2-107-20-18-109.compute-1.amazonaws.com
    - ec2-54-196-180-60.compute-1.amazonaws.com
    - ec2-54-82-80-169.compute-1.amazonaws.com
    - ec2-54-167-125-16.compute-1.amazonaws.com
    - ec2-54-234-100-79.compute-1.amazonaws.com
    - ec2-54-90-70-2.compute-1.amazonaws.com
    - ec2-107-20-97-152.compute-1.amazonaws.com
    - ec2-107-20-68-197.compute-1.amazonaws.com
    - ec2-54-146-205-66.compute-1.amazonaws.com
    - ec2-54-147-154-109.compute-1.amazonaws.com
    - ec2-54-160-145-147.compute-1.amazonaws.com
    - ec2-54-242-113-71.compute-1.amazonaws.com
    - ec2-54-91-104-208.compute-1.amazonaws.com
    - ec2-54-90-184-255.compute-1.amazonaws.com
    - ec2-54-226-177-118.compute-1.amazonaws.com
    - ec2-54-221-29-172.compute-1.amazonaws.com
    - ec2-54-196-157-69.compute-1.amazonaws.com
    - ec2-54-242-32-246.compute-1.amazonaws.com
    - ec2-54-242-8-111.compute-1.amazonaws.com
    - ec2-54-91-113-225.compute-1.amazonaws.com
    - ec2-54-234-235-212.compute-1.amazonaws.com
    - ec2-54-242-42-94.compute-1.amazonaws.com
    - ec2-50-17-72-112.compute-1.amazonaws.com
    - ec2-107-20-14-218.compute-1.amazonaws.com
    - ec2-54-163-59-155.compute-1.amazonaws.com
    - ec2-184-72-140-54.compute-1.amazonaws.com
    - ec2-23-22-164-42.compute-1.amazonaws.com
    - ec2-54-234-124-12.compute-1.amazonaws.com
    - ec2-54-163-40-117.compute-1.amazonaws.com
    - ec2-54-163-194-209.compute-1.amazonaws.com
    - ec2-54-144-95-31.compute-1.amazonaws.com
    - ec2-54-144-85-65.compute-1.amazonaws.com
    - ec2-54-91-203-191.compute-1.amazonaws.com
    - ec2-54-87-32-41.compute-1.amazonaws.com
    - ec2-54-90-230-217.compute-1.amazonaws.com
    - ec2-54-145-17-101.compute-1.amazonaws.com
    - ec2-54-196-252-146.compute-1.amazonaws.com
    - ec2-107-20-93-138.compute-1.amazonaws.com
    - ec2-23-22-169-33.compute-1.amazonaws.com
    - ec2-107-20-12-25.compute-1.amazonaws.com
    - ec2-54-90-138-73.compute-1.amazonaws.com
    - ec2-23-22-210-97.compute-1.amazonaws.com
    - ec2-54-159-14-101.compute-1.amazonaws.com
    - ec2-54-92-195-82.compute-1.amazonaws.com
    - ec2-54-159-0-151.compute-1.amazonaws.com
    - ec2-50-17-84-80.compute-1.amazonaws.com
    - ec2-54-221-6-237.compute-1.amazonaws.com
    - ec2-54-147-143-89.compute-1.amazonaws.com
    - ec2-54-163-223-132.compute-1.amazonaws.com
Are you sure you want to destroy this cluster? [y/N]: y
Destroying dale-lsh...
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flintrock/flintrock.py", line 804, in main
    cli(obj={})
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flintrock/flintrock.py", line 332, in destroy
    cluster.destroy()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flintrock/ec2.py", line 118, in destroy
    Groups=[flintrock_base_group.id])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/boto3/resources/factory.py", line 455, in do_action
    response = action(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/boto3/resources/action.py", line 79, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/botocore/client.py", line 407, in _make_api_call
    raise ClientError(parsed_response, operation_name)
An error occurred (InvalidParameterCombination) when calling the ModifyInstanceAttribute operation: You may only modify the groupSet attribute for VPC instances
```

### LINKED ISSUE #92: Launching VPC cluster throws the error: "Exception: Error authorizing cluster ingress to self"
When I try to launch a cluster into a vpc. I get this error: "Exception: Error authorizing cluster ingress to self"

See https://github.com/nchammas/flintrock/issues/85 for more details

### PR DESCRIPTION
**Pull request by nchammas**
The discussion in #85 and #92 revealed that Flintrock has thus far assumed that everyone works with a default VPC, and this is not true. If you created your AWS account in or before 2013, you very likely don't have a default VPC.

This PR adds support for non-default VPCs. The relevant reading is here:

* http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/default-vpc.html
* https://forums.aws.amazon.com/thread.jspa?messageID=707417
* https://github.com/mitchellh/packer/issues/1935#issuecomment-111235752

To summarize the key points from the above links, as well as the key changes in this PR:

1. Security groups are scoped to a VPC, and Flintrock clusters are identified by security group. This means that all Flintrock commands that need to identify a cluster now accept a VPC parameter.
2. If you do not specify the VPC you want, Flintrock will query EC2 for the default VPC in your region. This is how Flintrock worked before this PR, but now that logic has been formalized and Flintrock will give a clean error message if you have no default VPC set in your selected region.
3. When you specify the VPC explicitly, Flintrock assumes it's a non-default VPC and requires that you specify a subnet explicitly since users currently are unable to set default subnets on non-default VPCs. Flintrock will additionally check that your non-default VPC and subnet are configured correctly.

@dhulse @marcuscollins - I've tested this PR thoroughly, but it would be a big help if you tested this in your environments and confirmed that it works for you as expected. The key things to test are the 3 points I just laid out above.

To install Flintrock at this PR, use this command:

```
pip3 install -U git+https://github.com/nchammas/flintrock@non-default-vpc
```

This will override any installation of Flintrock you have in your currently-active environment.

Fixes #85.
Fixes #92.

### CODE REVIEW

**Comment by marcuscollins** [comment]
@nchammas It launches into the (non-default) VPC and does have the specified IAM role, but still can't access s3 w/o specifying key id and secret key.

**Comment by nchammas** [comment]
Regarding S3 access, can you post the IAM policy as well as the S3 location you are trying to access? At this point I think this is most likely a problem with your IAM policy.

Also, can you confirm that Flintrock errors out cleanly if you try a launch without setting a VPC explicitly (since you don't have a default VPC)?

**Comment by marcuscollins** [comment]
Errors out correctly:
```Flintrock could not find a default VPC in us-east-1. Please explicitly specify a VPC to work with in that region. Flintrock does not support managing EC2 clusters outside a VPC.
```

**Comment by marcuscollins** [comment]
The s3 loc is private, so I can't pass it along, sorry. I suspect you are correct though, and I'll look into it.

**Comment by nchammas** [comment]
In case it helps, a common problem with S3 policies is that they don't grant the following 3 rights--list access, root access, and content access ([ref](http://andrewhitchcock.org/?post=325)):

```
{
  "Statement": [
    {
      "Action": [
        "s3:ListAllMyBuckets"
      ],
      "Effect": "Allow",
      "Resource": "arn:aws:s3:::*"
    },
    {
      "Action": "s3:*",
      "Effect": "Allow",
      "Resource": ["arn:aws:s3:::my-bucket", "arn:aws:s3:::my-bucket/*"]
    }
  ]
}
```

I've made this mistake in the past and it can be hard to catch if you don't know what to look for.

**Comment by marcuscollins** [comment]
Huh, ours is pretty generic:
```
{
  "Version": "2012-10-17", 
  "Statement": [
    {
      "Action": [
        "ec2:AuthorizeSecurityGroupIngress", 
        "ec2:CancelSpotInstanceRequests", 
        "ec2:CreateSecurityGroup", 
        "ec2:CreateTags", 
        "ec2:Describe*", 
        "ec2:DeleteTags", 
        "ec2:ModifyImageAttribute", 
        "ec2:ModifyInstanceAttribute", 
        "ec2:RequestSpotInstances", 
        "ec2:RunInstances", 
        "ec2:TerminateInstances", 
        "iam:PassRole", 
        "iam:ListRolePolicies", 
        "iam:GetRole", 
        "iam:GetRolePolicy", 
        "iam:ListInstanceProfiles", 
        "s3:Get*", 
        "s3:List*", 
        "s3:CreateBucket", 
        "sdb:BatchPutAttributes", 
        "sdb:Select"
      ], 
      "Resource": "*", 
      "Effect": "Allow"
    }
  ]
}
```
I'll look up what other s3 operations there might be that I'd need, and I'll see if I can get permission to create a simple role like that one to test out. I wonder if this is just going to end up being YAA pre-2013 issue.

**Comment by nchammas** [comment]
Your policy is missing the `s3:ListAllMyBuckets` action. I wonder if that's the missing permission you need.

**Comment by marcuscollins** [comment]
that isn't covered under "s3:List*"?

**Comment by nchammas** [comment]
Oh, sorry, you're right. :confused:

**Comment by nchammas** [comment]
Let's move the discussion about IAM roles to #90.

Since the non-default VPC launches work for you @marcuscollins, I'll just wait for @dhulse to also confirm that this PR works for him before merging it in.

**Comment by dhulse** [comment]
I have attempted to launch a cluster twice using the code from the PR. I no longer run into the error: "Exception: Error authorizing cluster ingress to self". However I still cannot create a cluster successfully.

Here is my output. (I am setting vpc-id and subnet-id in my config file)
```bash
flintrock launch dale-tiny2 --num-slaves 2
Requesting 3 spot instances at a max price of $0.2...
0 of 3 instances granted. Waiting...
0 of 3 instances granted. Waiting...
All 3 instances granted.
There was a problem with the launch. Cleaning up...
Do you want to terminate the 3 instances created by this operation? [Y/n]:
``` 
I may have something configured incorrectly on my side. I will continue to investigate.

**Comment by dhulse** [comment]
I have noticed that I cannot ssh into my ec2 instances as `ec2-user`. Perhaps I need to do some further configuration on my non default vpc

**Comment by nchammas** [comment]
Hmm, is there no explanatory error message when the launch fails, after you answer the prompt?

**Comment by dhulse** [comment]
No, it just says "here was a problem with the launch. Cleaning up..."

**Comment by nchammas** [comment]
Are you using a vanilla Amazon Linux AMI, or something else?

**Comment by nchammas** [comment]
If you newly created your VPC and subnet, you may need to attach an internet gateway. That's a mistake I've made before.

I'm confused though as to why there is no detail on the launch failure. That's definitely not good. :(

**Comment by dhulse** [comment]
I have been using `ami-60b6c60a` which is different from the default ami provided by flintrock `ami-60b6c60a`.  I tried launching a cluster using `ami-60b6c60a` instead and I still have the same issue.

I don't think an internet gateway has been attached to the new VPC I have created. I will look into that.

**Comment by nchammas** [comment]
Just checking in briefly here: @dhulse - Any progress on getting Flintrock working on this branch? Any leads I can help you investigate?

**Comment by nchammas** [comment]
Merging this in since the primary feature (launching into non-default VPCs) seems to be working.

**Comment by dhulse** [comment]
Hey @nchammas I have not had any progress on getting Flintrock to work in my VPC. I have been really busy with other priorities these past few days. I will investigate why it's not working on my side and will let you know what I find out. Thanks!

**Pull request merged**
