### PR TITLE
Add support for assigning IAM roles to launched instances

### LINKED ISSUE #37: Allow clusters to be assigned IAM roles during launch
When you launch a cluster you want to access a dataset somewhere, and that somewhere is often S3. You need credentials to access non-public locations on S3.

Instead of copying around AWS keys or doing some other janky setup, the Amazon-recommended way is to assign the instances in your cluster to an appropriate IAM role that lets them access what they need.

We should support this.

### PR DESCRIPTION
**Pull request by engrean**
I tested it manually and it works. I am not sure how to write an automated test for this.

Fixes #37.

### CODE REVIEW

**Comment by nchammas** [comment]
Hey @engrean, thanks for taking a crack at this! I edited your PR title and description to match the conventions we are using this project.

This looks good to me, but there is a style error that needs to be fixed on line 662. If you click on the details for the build (next to **continuous-integration/travis-ci/pr**) you should be able to see more information.

**Comment by nchammas** [comment]
Oh, and I forgot to add: Don't worry about adding a test for this. Many things in Flintrock are difficult to test, so a change like this doesn't need any specific tests added for now.

There are some testing improvements planned as part of #49.

**Comment by engrean** [comment]
Okay, sounds good. Thanks for your help.

**Comment by nchammas** [comment]
OK, I tested this and it works for me! The last thing to do @engrean before I can merge this in is to [squash your commits into one](https://github.com/nchammas/flintrock/blob/272c89b89d72b123d519e93527a2e05b41f5a5c7/CONTRIBUTING.md#capture-one-idea-in-one-pull-request).

If you need help with that, feel free to pop in to the [Flintrock Gitter room](https://gitter.im/nchammas/flintrock). I can also just do that for you if you prefer by opening a new PR based off of this one.

**Comment by engrean** [comment]
Okay, I think I did it right.
I went to sign onto gitter, but they want my to approve app access for the
orgs I am employed by. I couldn't find a way to uncheck it.

Regards,
Christian

**Comment by nchammas** [comment]
Looks good to me; merging this in. Thanks again for working on this!

**Pull request merged**
