### PR TITLE
Use a access_origins parameters for the security groups

### LINKED ISSUE #38: Give users an easy way to authorize new addresses to access a cluster
By default, Flintrock only authorizes the host it's running on to access launched clusters. So if you launch a cluster and then go somewhere else where your IP is gonna be different, you won't be able to login to the cluster anymore.

We should offer a way for users to authorize custom addresses on launch, and perhaps also a way for users to authorize their current address to access existing clusters.

### PR DESCRIPTION
**Pull request by rmessner**
This pull request is a partial/independant reply to the private VPC issue ( #14 )

Fixes #38.

### CODE REVIEW

**Comment by nchammas** [comment]
@rmessner - Can you elaborate on the purpose of this PR?

If it does not stand alone as a valuable feature, but instead is part of the private VPC work, then could you collapse this PR into #108?

I'd like a single PR to cover adding private VPC support to Flintrock.

**Comment by rmessner** [comment]
@nchammas - This feature alone allow user using Public Subnet to specify more than their own IP who is allowed to access spark pointed in this issue #38 .

But if you prefer a single PR anyway, i can easily merge it.

It's up to you

**Comment by nchammas** [comment]
Ah, I see now. Sorry, I didn't realize at first that this was about #38. (I added a note to that effect to the original PR text so that the issue automatically gets closed when this PR is merged.)

I think this is fine as a separate PR. I will look at it more closely this week.

**Comment by nchammas** [comment]
@rmessner - Now that you can associate specific security groups with a cluster on launch (#112), you can enable access to the cluster on any set of addresses via those security groups.

I prefer that approach since is it more general and since I think it can save us from having to add another option to the interface.

As a result, I'm going to close this PR. But please chime in if you disagree with my position or think I've missed something.

**Pull request closed without merging**
